repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
  hooks:
    - id: trailing-whitespace
      exclude: .*\.(m(?:d(?:te?xt|o?wn)?|arkdown|kdn?)|text)$
    - id: end-of-file-fixer

- repo: https://github.com/compilerla/conventional-pre-commit
  rev: v2.1.1
  hooks:
    - id: conventional-pre-commit
      stages: [commit-msg]
      args: []
