title: ShaunNope, Maybe Perhaps
description: A collection of all things Sean
baseurl: "" # the subpath of your site, e.g. /blog
domain: www.shaunnope.com
url: https://www.shaunnope.com

author:
  name: Sean Yap

show_excerpts: true
excerpt_separator: <!--more-->

remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag

minima:
  # Generate social links in footer.
  social_links:
    - {
      platform: github,
      user_url: "https://github.com/shaunnope",
      title: shaunnope
      }
    - {
      platform: linkedin,
      user_url: "https://www.linkedin.com/in/zhan-hao-sean-yap",
      title: zhan-hao-sean-yap
      }
    - {
      platform: email,
      user_url: "mailto:pages@shaunnope.com",
      title: email
      }

sidebar:
  - {
    text: "No Leap Day",
    url: "https://www.shaunnope.com/NoLeapDay"
  }
  - {
    text: "Chain Reaction",
    url: "https://www.shaunnope.com/ChainReaction"
  }


lynxi:
  - {
    text: "Tellonym",
    url: "https://tellonym.me/shaunnope"
  }
  - {
    text: "Linktree",
    url: "https://linktr.ee/shaunnope"
  }
  - {
    text: "Telegram",
    url: "https://t.me/+jAnDRT69eS9lYWE1",
  }
