title: ShaunNope, Maybe Perhaps
description: A collection of all things Sean
baseurl: "" # the subpath of your site, e.g. /blog
domain: www.shaunnope.com
url: https://www.shaunnope.com

remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme

minima:
  # Generate social links in footer.
  social_links:
    - {
      platform: github,
      user_url: "https://github.com/shaunnope",
      title: shaunnope
      }
    - {
      platform: linkedin,
      user_url: "https://www.linkedin.com/in/zhan-hao-sean-yap",
      title: zhan-hao-sean-yap
      }
    - {
      platform: email,
      user_url: "mailto:pages@shaunnope.com",
      title: email
      }


# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
